-- Run this against a MySQL 8.x server to provision the database by hand.
-- In dev, TypeORM's `synchronize: true` (src/config/data-source.ts) also
-- creates/updates these tables automatically from the entities on boot,
-- so running this script manually is optional but kept here as the
-- canonical, reviewable schema definition.
